Improved stuff.
...





Yes, these commit messages are lame. I'm tired, and nobody is going
to use this crap anyways, okay?

diff --git a/zsh/zshfw b/zsh/zshfw
--- a/zsh/zshfw
+++ b/zsh/zshfw
@@ -10,8 +10,12 @@ function zshfw_load_first() {
 }
 
 function zshfw_load_single_plugin() {
-    zsh_load_first "$1" || echo "zshfw: warning: cannot find plugin '$1'." >&2
-    "$1"_load
+    if [[ -z $(eval echo \${${1}_loaded}) ]]; then
+        zsh_load_first "$1" || \
+            echo "zshfw: warning: cannot find plugin '$1'." >&2
+        "$1"_load
+        export ${1}_loaded=1
+    fi
 }
 
 function loadplugin() {
@@ -25,17 +29,45 @@ function loadplugins() {
 }
 
 function loadtheme() {
+    if [[ -z $1 ]]; then
+        return
+    fi
+
     zsh_load_first "$1" || "zshfw: warning: cannot find theme '$1'." >&2
 }
 
 function unloadplugin() {
-    "$1"_unload
+    if [[ -z $1 ]]; then
+        return;
+    fi
+
+    if [[ -n $(eval echo \${${1}_has_unload}) ]]; then
+        ${1}_unload
+    else
+        echo "zshfw: no unload function for plugin '$1'." > &2
+    fi
 }
 
 function helpplugin() {
-    "$1"_help
+    if [[ -z $1 ]]; then
+        return;
+    fi
+
+    if [[ -n $(eval echo \${${1}_has_help}) ]]; then
+        ${1}_help
+    else
+        echo "zshfw: no help function for plugin '$1'." > &2
+    fi
 }
 
 function helptheme() {
-    "$1"_help
+    if [[ -z $1 ]]; then
+        return;
+    fi
+
+    if [[ -n $(eval echo \${${1}_has_help}) ]]; then
+        eval ${1}_help
+    else
+        echo "zshfw: no help function for theme '$1'." > &2
+    fi
 }
